title: Fuxian JIA's Homepage
page-top-title: Fuxian JIA
top-section-bg-text: Electronic Information Engineering
home-subtitle: Fuxian JIA&entp;|&entp;贾付贤
copyright-text: '&copy; Fuxian JIA 2023-2024. All Rights Reserved.'